
DIST_SOURCES := build/distenv.ml
export DIST_SOURCES

include bindings/Makefile.inc
include pintlib/Makefile.inc
include phlib/Makefile.inc
include contrib/Makefile.inc
include Makefile.inc

# vi:set syntax=make:
