
OPAM_VERSION = $(shell opam --version 2>/dev/null)
ifneq ($(OPAM_VERSION),)
	HAS_OPAM = 1
endif

ifdef HAS_OPAM
	OCAML_LIBDIR := $(shell opam config var lib)/
else
	OCAML_LIBDIR := +
endif


DIST_SOURCES := build/distenv.ml
export DIST_SOURCES

include bindings/Makefile.inc
include pintlib/Makefile.inc
include phlib/Makefile.inc
include anlib/Makefile.inc
include contrib/Makefile.inc

# vi:set syntax=make:
