
OCAML_LIBDIR=$(shell opam config var lib 2>/dev/null)
ifeq ($(OCAML_LIBDIR),)
	OCAML_LIBDIR := +
else
	OCAML_LIBDIR := $(OCAML_LIBDIR)/
endif


DIST_SOURCES := build/distenv.ml
export DIST_SOURCES

include bindings/Makefile.inc
include pintlib/Makefile.inc
include phlib/Makefile.inc
include anlib/Makefile.inc
include contrib/Makefile.inc
include Makefile.inc

# vi:set syntax=make:
