#!/usr/bin/env python3
"""
Copyright or © or Copr. Loïc Paulevé, Morgan Magnin, Olivier Roux (2010)

loic.pauleve@irccyn.ec-nantes.fr
morgan.magnin@irccyn.ec-nantes.fr
olivier.roux@irccyn.ec-nantes.fr

This software is a computer program whose purpose is to provide Process
Hitting related tools.

This software is governed by the CeCILL license under French law and
abiding by the rules of distribution of free software.  You can  use, 
modify and/ or redistribute the software under the terms of the
CeCILL license as circulated by CEA, CNRS and INRIA at the following URL
"http://www.cecill.info". 

As a counterpart to the access to the source code and  rights to copy,
modify and redistribute granted by the license, users are provided only
with a limited warranty  and the software's author, the holder of the
economic rights, and the successive licensors  have only  limited
liability. 

In this respect, the user's attention is drawn to the risks associated
with loading,  using,  modifying and/or developing or reproducing the
software by the user in light of its specific status of free software,
that may mean  that it is complicated to manipulate,  and  that  also
therefore means  that it is reserved for developers  and  experienced
professionals having in-depth computer knowledge. Users are therefore
encouraged to load and test the software's suitability as regards their
requirements in conditions enabling the security of their systems and/or 
data to be ensured and,  more generally, to use and operate it in the 
same conditions as regards security. 

The fact that you are presently reading this means that you have had
knowledge of the CeCILL license and that you accept its terms.
"""

# NOTE: converts the 'reaction' file of CNA into a Process Hitting.
#   http://www.mpi-magdeburg.mpg.de/projects/cna/manual/manual_cellnetanalyzer95.htm#_Toc261856171

import os
import sys

from pint_converter import *

reaction_file = sys.argv[1]
assert (os.path.basename(reaction_file) == "reactions"), "Give the file 'reactions' as parameter"

def explode_line(line):
    row = {}
    reqpart, parpart = line.replace("\t", " ").split("|")
    # reqpart
    reqpart = [f for f in reqpart.strip().split(" ") if f]
    reqpart.pop(0)

    reqpart = " ".join(reqpart)
    left, right = reqpart.split("=")

    def parse_cond(data):
        i, a = [f for f in data.strip().split(" ") if f]
        i = int(i)
        pos = a[0] != "!"
        if not pos:
            a = a[1:]
        return (a, i, pos)

    if not right.strip() :
        return None

    (a, i, pos) = parse_cond(right)
    assert pos

    conds = left.strip().split("+")
    conds = [parse_cond(h) for h in conds if h.strip()]

    row["Target"] = (a,i)
    row["Conds"] = conds

    # parpart
    parpart = [f for f in parpart.strip().split(" ") if f]
    row["Default"], row["Par1"], row["Par2"], row["Par3"] = parpart[0:4]

    return row

defs = {} # {a -> (maxlevel, default_value)}
interactions = {} # {a -> cond list}

def update_def(a, i, i0):
    if i0 is not None :
        try :
            i0 = int(i0)
        except:
            i0 = None
    old_i, old_i0 = defs.get(a, (0,0))
    i = max(i, old_i)
    assert i <= 1
    i0 = i0 if i0 is not None else old_i0
    defs[a] = (i, i0)


for line in open(reaction_file) :
    row = explode_line(line)
    if row is None :
        #print("Ignoring %s" % line, file=sys.stderr)
        continue
    elif row["Par3"] == '1' :
        print("Excluding %s" % row, file=sys.stderr)
        continue
    a, i = row["Target"]
    assert i == 1

    update_def(a, i, row["Default"] if not row["Conds"] else None)

    assert row["Par1"] == '0'

    if a not in interactions:
        interactions[a] = []
    interactions[a].append(row["Conds"])


sd = {}
init = []
for a, (maxlevel, default) in defs.items():
    sd[a] = list(range(maxlevel+1))
    init.append((a,default))

dep = {}
K = {}
for a, dnf in sorted(interactions.items()):

    bs = set()
    for c in dnf:
        bs.update([a for (a,_,_) in c])
    bs = list(sorted(bs))
    dep[a] = bs

    if not bs:
        continue

    ibs = dict([(b,i) for (i,b) in enumerate(bs)])

    def f(x):
        for c in dnf:
            match = True
            for (b, k, pos) in c:
                if not pos:
                    k = 1-k
                ib = ibs[b]
                match = x[ib] == k
                if not match:
                    break
            if match:
                return 1
        return 0

    K[a] = Kinit(sd, a)
    for x in State(sd, bs):
        K[a][f(x)].add(x)

K2an(sd, dep, K, init)

