#!/usr/bin/env python3
# -*- coding: utf-8
"""
Copyright Loïc Paulevé <loic.pauleve@lri.fr> (2014)

This software is a computer program whose purpose is to provide Process
Hitting related tools.

This software is governed by the CeCILL license under French law and
abiding by the rules of distribution of free software.  You can  use, 
modify and/ or redistribute the software under the terms of the
CeCILL license as circulated by CEA, CNRS and INRIA at the following URL
"http://www.cecill.info". 

As a counterpart to the access to the source code and  rights to copy,
modify and redistribute granted by the license, users are provided only
with a limited warranty  and the software's author, the holder of the
economic rights, and the successive licensors  have only  limited
liability. 

In this respect, the user's attention is drawn to the risks associated
with loading,  using,  modifying and/or developing or reproducing the
software by the user in light of its specific status of free software,
that may mean  that it is complicated to manipulate,  and  that  also
therefore means  that it is reserved for developers  and  experienced
professionals having in-depth computer knowledge. Users are therefore
encouraged to load and test the software's suitability as regards their
requirements in conditions enabling the security of their systems and/or 
data to be ensured and,  more generally, to use and operate it in the 
same conditions as regards security. 

The fact that you are presently reading this means that you have had
knowledge of the CeCILL license and that you accept its terms.
"""

import sys

from xml.dom.minidom import parse

inputname = sys.argv[1]

ginml = parse(inputname)

out = sys.stdout

# nodes definitions
N = {}
nodes = ginml.getElementsByTagName("node")
for node in nodes :
    a = node.getAttribute("id")
    la = int(node.getAttribute("maxvalue"))
    N[a] = la
    out.write("%s %d\n" % (a, la))
out.write("\n")

# fetch node parents
R = {}
edges = ginml.getElementsByTagName("edge")
for edge in edges :
    a = edge.getAttribute("from")
    t = int(edge.getAttribute("minvalue"))
    b = edge.getAttribute("to")
    if b not in R:
        R[b] = set()
    R[b].add(a)
for a in R.keys():
    R[a] = tuple(sorted(R[a]))

class State:
    def __init__(self, nodes):
        self.nodes = nodes
    def next(self, x):
        end = True
        for i in range(len(self.nodes)):
            if x[i] == N[self.nodes[i]]:
                x[i] = 0
            else:
                end = False
                x[i] += 1
                break
        return not end

    def __iter__(self):
        x = [0]*len(self.nodes)
        yield tuple(x)
        while self.next(x):
            yield tuple(x)

# fetch parameters
for node in nodes:
    a = node.getAttribute("id")
    if a not in R:
        continue
    P = {}
    bs = R[a]
    s = State(bs)
    for x in s:
        P[x] = 0

    for p in node.getElementsByTagName("parameter"):
        k = int(p.getAttribute("val"))
        i = p.getAttribute("idActiveInteractions").split()
        y = dict([(b,0) for b in bs])
        for j in i:
            z = j.split(":")
            b = z[0]
            if len(z) == 3:
                v = int(z[2])
            else:
                v = 1
            y[b] = v
        x = tuple([y[b] for b in bs])
        P[x] = k

    out.write("parameters for %s with %s\n" % (a, ",".join(bs)))
    for x, k in sorted(P.items()):
        out.write("%s   %d\n" % (" ".join(map(str,x)), k))
    out.write("\n")

