#!/usr/bin/env python
"""
Usage:
signedsif2ph file.sif > file.ph
or
signedsif2ph < file.sif > file.ph
"""

import re
import sys

if len(sys.argv) > 1:
	ifstream = open(sys.argv[1])
else:
	ifstream = sys.stdin

s2sign = {"1": "+", "-1": "-"}

sorts = set()
interactions = []

for line in ifstream:
	line = line.strip()
	if not line:
		continue
	a, s, b = re.split("\s+", line)
	sorts.update([a,b])
	interactions.append("%s 1 -> %s %s" % (a, s2sign[s], b))

print("process %s 1" % " 1\nprocess ".join(sorts))
print("BRN([\n%s\n])" % ";\n".join(interactions))


