
SOURCES := \
	util.ml\
	graph.ml\
	decision.ml\
	dynamic.ml\
	spec.ml\
	constraint.ml\
	valuation.ml\
	spig.ml\
	inference.ml\
	\
	brg.ml\
	logical.ml\
	polynome.ml\

LIBS := nums

# vi:set syntax=make:
