
SOURCES := \
	util.ml\
	types.ml\
	graph.ml\
	polynome.ml\
	decision.ml\
	dynamic.ml\
	spec.ml\
	constraint.ml\
	valuation.ml\
	spig.ml\
	inference.ml\
	\
	brg.ml\
	logical.ml\
	goal.ml\
	spim.ml\
	\
	ph_types.mli\
	ph_parser.mly\
	ph_lexer.mll\
	ph.ml\

LIBS := nums

# vi:set syntax=make:
